# Generated by Django 5.1.2 on 2024-11-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short answer'), ('LA', 'Long answer'), ('DD', 'Drop down'), ('DT', 'Date and time')], default='TEXT', max_length=20),
        ),
    ]
