# Generated by Django 5.1.2 on 2024-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time'), ('IMG', 'Image')], default='TEXT', max_length=20),
        ),
    ]
