# Generated by Django 5.1.2 on 2024-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_answer_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.CharField(default='miscillineous', max_length=40),
        ),
    ]
