# Generated by Django 5.1.2 on 2024-11-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_form_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='type',
            new_name='form_type',
        ),
    ]
