# Generated by Django 5.1.2 on 2024-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_rename_type_form_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_image',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time')], default='TEXT', max_length=20),
        ),
    ]
