# Generated by Django 5.1.2 on 2024-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollset',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
