# Generated by Django 5.1.2 on 2024-11-08 09:17

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollset_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollset',
            name='closed_at',
            field=models.DateTimeField(default=polls.models.poll_close_time),
        ),
    ]
