# Generated by Django 5.1.2 on 2024-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_picture',
            field=models.ImageField(blank=True, upload_to='profile_background/'),
        ),
    ]
