# Generated by Django 5.1.2 on 2024-11-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='John Doe Business space', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_picture',
            field=models.ImageField(blank=True, default='../static/assets/img/profile_default/background.png', upload_to='profile_background/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Meow meow', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(default='https://github.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='insta',
            field=models.CharField(default='https://www.instagram.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='John Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/assets/img/profile_default/logo.jpeg', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(default='https://www.twitter.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(default='https://example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofilereadme',
            name='content',
            field=models.TextField(blank=True, default="\n    # Nexify - Management & Progress Tracking Platform\n\n    Welcome to **Nexify**! This platform is designed to streamline the management, tracking, and accountability of club activities, goals, and progress. Whether you're leading a team or a member of a club, Nexify makes it easy to stay on top of your responsibilities and engage in meaningful progress tracking.\n\n    ## Features\n\n    - **Club Management**: Easily manage your clubs, societies, or teams. Assign roles and track club activities with ease.\n    - **Task & Goal Tracking**: Create, assign, and track tasks and goals for your club members, ensuring accountability.\n    - **Progress Monitoring**: Visualize progress over time with dynamic charts, logs, and reports.\n    - **User Roles**: Different roles like Admin and Member, with customizable access to manage club events and activities.\n    - **Event Management**: Organize events, track participation, and send reminders to members.\n    - **Notifications**: Get timely notifications about upcoming tasks, deadlines, and updates.\n    - **Communication Tools**: Streamlined communication channels for better coordination between club members.\n\n    ## Getting Started\n\n    ### Prerequisites\n\n    Before getting started with Nexify, ensure you have the following:\n    - A modern web browser (e.g., Chrome, Firefox)\n    - A registered account on **Nexify** (Sign up on the platform)\n"),
        ),
    ]
