# Generated by Django 5.1.2 on 2024-11-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemovement',
            name='movement_id',
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.fileupload'),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='short_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
