# Generated by Django 5.1.2 on 2024-11-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_filemovement_movement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemovement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_movements', to='tracking.fileupload'),
        ),
    ]
