# Generated by Django 5.1.2 on 2024-11-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_filemovement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemovement',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=40, null=True),
        ),
    ]
