# Generated by Django 5.1.2 on 2024-11-08 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_json_metadata', models.TextField(blank=True, default='"class": "go.TreeModel","nodeDataArray":', null=True)),
                ('json_data', models.TextField(default='{"class": "go.TreeModel", "nodeDataArray": []}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_pk', models.IntegerField(unique=True)),
                ('branch_pk', models.IntegerField(unique=True)),
                ('background_image', models.ImageField(blank=True, default='../static/assets/img/club_default/background.jpeg', null=True, upload_to='clubs_background/')),
                ('logo_image', models.ImageField(blank=True, default='../static/assets/img/club_default/logo.jpeg', null=True, upload_to='clubs_logo/')),
                ('club_name', models.CharField(max_length=100, unique=True)),
                ('club_subtext', models.CharField(blank=True, max_length=100)),
                ('club_description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club Detail',
                'verbose_name_plural': 'Club Details',
                'ordering': ['club_name'],
                'indexes': [models.Index(fields=['club_name'], name='club_clubde_club_na_0e2250_idx'), models.Index(fields=['club_pk', 'branch_pk'], name='club_clubde_club_pk_9359b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_pk', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], default='Member', max_length=50)),
                ('power', models.PositiveIntegerField(default=1, help_text="Assign a numeric value representing the user's power level (higher number = higher power).")),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.clubdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'ordering': ['-member_since'],
                'indexes': [models.Index(fields=['club', 'user'], name='club_clubme_club_id_368807_idx'), models.Index(fields=['power'], name='club_clubme_power_acfce9_idx')],
                'unique_together': {('club', 'user')},
            },
        ),
    ]
