# Generated by Django 5.1.2 on 2024-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdata',
            name='fixed_json_metadata',
            field=models.TextField(blank=True, default='"class": "go.TreeModel","nodeDataArray":', null=True),
        ),
        migrations.AlterField(
            model_name='clubdata',
            name='json_data',
            field=models.TextField(),
        ),
    ]
