# Generated by Django 5.1.2 on 2024-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='branch_pk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='club_pk',
            field=models.IntegerField(),
        ),
    ]
