# Generated by Django 5.1.2 on 2024-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_clubdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdata',
            name='json_data',
            field=models.TextField(default='{"class": "go.TreeModel", "nodeDataArray": [{"key": 1, "name": "Stella Payne Diaz", "title": "CEO", "dept": "Management", "pic": "1.jpg", "email": "sdiaz@example.com", "phone": "(234) 555-6789"}]}'),
        ),
    ]
