# Generated by Django 5.1.2 on 2024-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_clubdata_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdata',
            name='json_data',
            field=models.TextField(default='{"class": "go.TreeModel", "nodeDataArray": []}'),
        ),
    ]
