# Generated by Django 5.1.2 on 2024-11-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_clubjoinrequest_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('Head', 'Head'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('HOD', 'HOD'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Member', 'Member')], default='Member', max_length=50),
        ),
    ]
